# Generated by Django 3.2.7 on 2023-01-14 20:59

from django.db import migrations, models
import programmingProphet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('descriptions', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('comments', models.JSONField(default=programmingProphet.models.default_list)),
                ('avgrate', models.IntegerField()),
                ('type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractionTitle', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractionTitle', models.CharField(default='', max_length=255)),
                ('commentTitle', models.CharField(default='', max_length=255)),
                ('comment', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractionTitle', models.CharField(default='', max_length=255)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
