# Generated by Django 3.2.7 on 2023-01-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingProphet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
